### PR TITLE
Use mkdocs for doc site

### PR DESCRIPTION
**Pull request by cccs-eric**
Introduction of `mkdocs` to generate a site that will be used by Copilot. 

Once this is merged in, we would need to create a step in the build pipeline to automatically call `mkdocs gh-deploy`, which will make the doc available [here](https://cybercentrecanada.github.io/jupyterlab-sql-editor).

### CODE REVIEW

**Comment by cccs-nik** [comment]
Mind reverting the changes to package-lock.json @cccs-eric ? I know the current one in main is a tiny bit out-of-date but you regenerated the lock file with an older version of npm. It might break stuff.

**Comment by cccs-eric** [comment]
oh, sorry!  Did not realize this.  What is the proper way of generating the proper lock file?

**Comment by cccs-nik** [comment]
You didn't modify package.json so I wouldn't worry about it, I would just revert the current changes and it should be good to go!

**Comment by cccs-eric** [comment]
> You didn't modify package.json so I wouldn't worry about it, I would just revert the current changes and it should be good to go!

But I did modify setup.py (I added a dependency).  I guess since it is not a dependency that is required to run the extension (it is only used at build time), no need to modify package.json?

**Review by cccs-nik — APPROVED** [review]

**Review by cccs-jc — APPROVED** [review]
I'll look at the docs generated and give feedback that way. Not much point on checking in the diff.

**Pull request merged**
